<?php

/**
 * @file
 * Contains taxonomy_terms_import_with_field.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function taxonomy_terms_import_with_field_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the taxonomy_terms_import_with_field module.
    case 'help.page.taxonomy_terms_import_with_field':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module will import terms from csv for perticula vocabulary[D[D[D[D[D[D[D[D[D[D[Dr v[3~[3~[3~[3~[2~ocabulary.') . '</p>';
      return $output;

    default:
  }
}
