# Schema for the configuration files of the twittershake module.
twittershake.settings:
  type: config_object
  label: 'twittershake settings'
  mapping:
    example:
      type: string
      label: 'Example'
